name:HeterocycleReactivityML 
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.3.4
  - numpy=1.19.5
  - pandas=1.1.5
  - python=3.6.13
  - rdkit=2020.09.3
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - seaborn=0.11.0
